# Generated by Django 5.2.4 on 2025-07-30 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('boss', 'Boss'), ('bau', 'Baú'), ('mob', 'Mob'), ('quest', 'Quest'), ('achievement', 'Achievement')], max_length=20)),
                ('imagem', models.ImageField(upload_to='mapas/')),
                ('ponto_referencia', models.TextField(blank=True, null=True)),
                ('ilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes', to='mapa.ilha')),
            ],
        ),
        migrations.DeleteModel(
            name='Localizacao',
        ),
    ]
