# Generated by Django 5.2.4 on 2025-07-31 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_informacao_delete_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilha',
            name='icone',
            field=models.ImageField(default='icones/default.png', upload_to='icones_ilhas/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informacao',
            name='ilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='mapa.ilha'),
        ),
        migrations.AlterField(
            model_name='informacao',
            name='imagem',
            field=models.ImageField(upload_to='localizacoes/'),
        ),
    ]
