# Generated by Django 5.2.4 on 2025-07-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_ilha_icone_alter_informacao_ilha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacao',
            name='recompensa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
